### ISSUE TITLE
Creación de la Base de Datos

### ISSUE THREAD

**Issue by Edwar-Forero** [Edwar-Forero/SistemaGestionDeTickets#4]
Asunto para diseñar las tablas necesarias para la base de datos

**Comment by JandiRamirez0814** [comment]
La base de datos fue creada desde MySql, siendo tres tablas principales:

- Empleados
- Usuarios (Clientes)
- Tickets

Los tickets son creados por los usuarios, parte de su información, puede ser editada a excepción de variables como el ID del ticket, su fecha de vencimiento o creación y su estado.

Los empleados pueden atender tickets más no editar ellos mismos la información de estos. Cuando la revisión (atención o proceso de atender el ticket) finaliza, el estado del ticket cambia.

Los tickets pueden ser vistos por ambos, usuarios y empleados.
